config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :cocktails, only: [ :index, :show, :new, :create] do
  resources :dose, only: [ :create ]
end
resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
has_many :doses, dependent: :destroy
has_many :ingredients, through: :doses
validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord

  belongs_to :cocktail
  belongs_to :ingredient
  #validates :cocktail, :ingredient, uniqueness: true
  validates :description, presence: true
  validates_uniqueness_of :ingredient_id, :scope => [ :cocktail_id ]

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: false
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end
  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
    redirect_to cocktail_path(@cocktail)
    else
    render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Want a Cocktail babe?</h1>
<p>
  <% @cocktails.each do |cocktail| %>
  <li><%= link_to cocktail.name, cocktail_path(cocktail)%></li>
  <% end %>
</p>

<%= link_to '+add a Cocktail', new_cocktail_path, class: "btn btn-primary btn-lg" %>

app/views/cocktails/new.html.erb
<h1>Create a new Cocktail babe</h1>
    <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>

app/views/cocktails/show.html.erb
<h1> Cocktail:<strong> <%= @cocktail.name %></strong></h1>
<p> <%=%></p>

<div>
  <table class="table table-bordered">
<tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
</div>


<div class="col-sm-12 col-md-6">
      <%= render 'doses/new', cocktail: @cocktail, dose: @dose %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <h3>Reviews</h3>
      <% if @cocktail.reviews.empty? %>
        <p>Be the first to let a review</p>
      <% else %>
        <ul class="list-group">
          <% @cocktail.reviews.each do |review| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <span class="badge badge-primary badge-pill">
                <% counter = 0 %>
                <% 5.times do %>
                  <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                  <% counter += 1 %>
                <% end %>
              </span>
              <%= review.content %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

<%= link_to "create dose with ingredients", new_cocktail_dose_path(@cocktail) %>
<%=link_to "Back to Cocktails' list", cocktails_path %>

app/views/doses/new.html.erb
<h1>Add a new dose</h1>

<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>